config/routes.rb
Rails.application.routes.draw do
  root 'news_papers#index'
  resources :news_papers do 
    resources :articles do 
      resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
        belongs_to :news_paper, optional: true
        has_many :comments,  dependent: :destroy
        validates :title, presence: true 
        validates :body, presence: true, length: { minimum: 10 }

                   
end
    

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/concerns/custom_validation.rb
class MyValidator < ActiveModel::Validator
    def validate(record)
        unless record.title.start_with? 'X'
          record.errors.add :title, "Need a name starting with X please!"
        end
      end
    end

    class Person
        include ActiveModel::Validations
        validates_with MyValidator
     end

app/models/news_paper.rb
class NewsPaper < ApplicationRecord
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActionController::MimeResponds
    before_action :welcome_artical, only: [:new]
    after_action :blog_created, only: [:create]
    
    def index
        @newspaper = NewsPaper.find(params[:news_paper_id])
        @articles = @newspaper.articles
      end
    
      def show
        @newspaper = NewsPaper.find(params[:news_paper_id])
        @article = @newspaper.articles.find(params[:id])
      end
    
      def new
        @newspaper = NewsPaper.find(params[:news_paper_id])
        @article = @newspaper.articles.new
      end
    
      def create
        @newspaper = NewsPaper.find(params[:news_paper_id])
        @article = @newspaper.articles.create(article_params)
        if @article.save!
          redirect_to news_paper_articles_path
        else
          render :new
        end
      end

  def edit
    @newspaper = NewsPaper.find(params[:news_paper_id])
    @article = @newspaper.articles.find(params[:id])
  end

  def update
    @newspaper = NewsPaper.find(params[:news_paper_id])
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to news_paper_article_path(@newspaper, @article)
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end  

  private

  def welcome_artical
    puts "Welcome to new blog"  
  end  


  def blog_created
    puts "Blog is created"  
    flash[:alert] = "Blog is created"

  end  

  private
  def article_params
    params.require(:article).permit(:title, :body ,:news_paper_id)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    def destroy
        @article = Article.find(params[:id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
      end
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/news_papers_controller.rb
class NewsPapersController < ApplicationController
  def index
    @newspapers=NewsPaper.all
  end
  def show
    @newspapers = NewsPaper.find(params[:id])
  end
  def new
    @newspapers = NewsPaper.new
  end

  def create
    @newspapers = NewsPaper.new(news_paper_params)
    if @newspapers.save
      redirect_to news_papers_path
    else
      render :new
    end
  end
  def destroy
    @newspaper = NewsPaper.find(params[:id])
    @newspaper.destroy
    redirect_to news_papers_path
  end

  private
    def news_paper_params
      params.require(:news_paper).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/new_papers_helper.rb
module NewPapersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: [ @newspaper, @article ], local: true) do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <%= form.hidden_field :news_paper_id %>
    
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1>Welcome to Article!</h1>

<p>Here you can publish your Article</p>

<h1>Articles</h1>
<ul>
  <% @newspaper.articles.each do |article| %>
    <li>
    <%= link_to article.title, news_paper_article_path(news_paper_id: @newspaper.id, id: article.id) %>
      </a>
    </li>
  <% end %>
</ul>
<%= link_to "New Article", new_news_paper_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<ul>
  <li><%= link_to "Edit", edit_news_paper_article_path(@newspaper, @article) %></li>
  <li><%= link_to "Delete", news_paper_article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <li><%= link_to "Home", news_paper_articles_path %></li>
 
</ul>

app/views/comments/_comment.html.erb
<p>
<strong>Commentor:</strong>
<%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.Comment.build ], local: true)do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news_papers/_form.html.erb
<%= form_with model: @newspapers do |form| %>
    <%= form.label :name%><br>
    <%= form.text_field :name %>
    </div>
    <div>
      <%= form.submit %>
    </div>
<% end %>
  

app/views/news_papers/index.html.erb
<h1>NewsPapers</h1>
<h2>You can now create yours own Newspaper!</h2>
<ul>
  <% @newspapers.each do |newspaper| %>
    <li>
    <%= link_to newspaper.name, news_paper_articles_path(news_paper_id: newspaper.id) %>
  </li>

<%= link_to "Delete",news_paper_path(newspaper),
method: :delete,
data: { confirm: "Are you sure?" } %>
  <% end %>
</ul>

<%= link_to "New Newspaper", new_news_paper_path %>

app/views/news_papers/new.html.erb
<h1>New Newspaper</h1>

<%= render "form"%>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>